### ISSUE TITLE
Crashing on Google Play automated tests

### ISSUE THREAD

**Issue by marticliment** [griush/GalileoHack#40]
@griush, crec que aquesta és la part de la UI que vas fer tu.

Està petant alguns dels automated google play tests.

```logcat
java.lang.IllegalStateException: Fragment GeneralStatsPage{3084d26} (43dc5ece-894a-41d7-84df-0faf3dc03bfa) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:1036)
	at androidx.fragment.app.Fragment.getString(Fragment.java:1058)
	at com.gnsstracker.mainapp.ui.GeneralStatsPage.DrawCapabilities(GeneralStatsPage.java:107)
	at com.gnsstracker.mainapp.ui.GeneralStatsPage.-$$Nest$mDrawCapabilities(Unknown Source:0)
	at com.gnsstracker.mainapp.ui.GeneralStatsPage$1.lambda$run$0(GeneralStatsPage.java:96)
	at com.gnsstracker.mainapp.ui.GeneralStatsPage$1.$r8$lambda$9WGeNDfiMmFdyNPM20c7lfs_zL4(Unknown Source:0)
	at com.gnsstracker.mainapp.ui.GeneralStatsPage$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:240)
	at android.app.ActivityThread.main(ActivityThread.java:8000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

[Vídeo del Crash](https://github.com/user-attachments/assets/79286b0d-0b97-444e-8b01-d76b888c731e)
[logcat.txt](https://github.com/user-attachments/files/16896753/logcat.txt)

**Comment by marticliment** [comment]
![image](https://github.com/user-attachments/assets/5db5b1a2-2498-49d6-9ab7-bde42caf1947)

**Comment by griush** [comment]
@marticliment, no consegueixo replicar el crash. Ni en el meu dispositiu ni en emulador.

**Comment by marticliment** [comment]
Posa tota la funció com.gnsstracker.mainapp.ui.GeneralStatsPage.DrawCapabilities dins d'un try catch

**Comment by griush** [comment]
en teoria segons la info del crash, falla un getString(), pero no se per que, en teoria `not attached to a context.` Pot ser es per que la id `unknown` no es valida en alguna versio rara? https://github.com/griush/GalileoHack/blob/master/GalileoFront/app/src/main/java/com/gnsstracker/mainapp/ui/GeneralStatsPage.java#L107

**Comment by marticliment** [comment]
El crash passa quan canvia de pàgina, pel que intueixo que en part la causa és el fet que el fragment no estigui en cap view, I, que per tant, no tingui el context de l'activitat. (getContext). Segurament el getstring i el resource manager hi estiguin relacionats.

**Comment by griush** [comment]
pel video sembla que es quan el timer actualitza el fragment, pero igualment, es raro que passi aquest crash i no ha passat mai a ningú a part del tester del play store... de moment ho deixo aixi, si passa a ser un problema ja ho estudiaré més

**Comment by marticliment** [comment]
a mi a l'estiu em va passar algun cop, però no vaig aconseguir reproduïr el bug.

Bueno, si es tornen a queixar ja et dic
